[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name='libreCalphad'
version='0.1.0'
authors=[
    {name = 'Matt Frichtl'},
]
dependencies = [
    "ESPEI",
    "pycalphad",
    "pymatgen",
    "matplotlib",
    "numpy",
    "pandas",
    "PyYAML",
    "scipy",
    "seaborn",
    "symengine",
    "sympy",
    "tinydb",
]
requires-python = ">=3.11"
description='Open-source Calphad databases and property models.'
license={text = 'MIT'}
#provides='libreCalphad'
classifiers=[
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    'Development Status :: 3 - Alpha',

    # Indicate who your project is intended for
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Physics',
    'Topic :: Scientific/Engineering :: Chemistry',

    # Pick your license as you wish (should match "license" above)
    'License :: OSI Approved :: MIT License',

    # Supported Python versions
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
]
[project.optional-dependencies]
propertyModels = ['kaleido', 'odfpy', 'pandarallel', 'scikit-learn', 'seaborn']
test = ['pytest']

[tool.setuptools.packages.find]
namespaces = false
include = ["libreCalphad*"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
"libreCalphad.databases" = ["*.tdb", "*.json"]
"libreCalphad.models.martensite_start" = ["*.pkl"]
"libreCalphad.models.martensite_start.model_params" = ["*.json"]
"libreCalphad.tests.test_database_files" = ["*.tdb", "*.xml"]
"libreCalphad.tests.test_datasets" = ["*.json"]
"libreCalphad.tests.test_heat_capacity_files" = ["*.json"]
"libreCalphad.tests" = ["*.csv"]
